TelegramBot:
    TelegramBotToken: '${TG_BOT_TOKEN}'
    DebugEnabled: true
    UpdateTimeout: 60
    WorkerCount: 8
    UserTableName: 'users'
Postgres:
    Host: 'localhost'
    Port: ${PG_PORT}
    User: '${PG_USER}'
    Password: '${PG_PASSWORD}'
    DbName: '${PG_DB}'